stages:
  - build
  - deploy

variables:
  IMAGE_NAME: nginx_ssl_on
  IMAGE_TAG: 1.0.0
  REGISTRY_USER: konansakh11

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker build -t $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker pull $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker run -d --name $IMAGE_NAME $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker exec $IMAGE_NAME sh -c "curl -vk https://localhost:443"
